### ISSUE TITLE
读取 src/main.js 模版可能出错

### ISSUE THREAD

**Issue by kankungyip** [F-loat/mpvue-entry#1]
如果main.js不在src目录下，将导致错误，建议可以自定义main.js的路径。

**Comment by F-loat** [comment]
后面可以考虑支持，但是感觉不是很有必要吧

**Comment by F-loat** [comment]
已修复，通过第二个参数传入 main.js 的路径即可，但需要放在 src 文件夹内，使得 babel 会对其进行处理
