### ISSUE TITLE
使用你提供最新的模板，关闭小程序会报错

### ISSUE THREAD

**Issue by ivanlee93** [F-loat/mpvue-entry#101]
![image](https://user-images.githubusercontent.com/22174857/50878836-75838b00-1413-11e9-82b3-8dc166c40570.png)

**Comment by F-loat** [comment]
关闭小程序是什么意思

**Comment by ivanlee93** [comment]
我刚刚看了，官方模板也会报错，就是右上角关闭小程序。比如调用上传图片接口，会离开小程序，离开小程序的时候就会报错

**Comment by ivanlee93** [comment]
好在不会影响代码执行

**Comment by F-loat** [comment]
估计是 mpvue 本身的问题了
