### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by keycz** [F-loat/mpvue-entry#105]
Module build failed: Error: Final loader didn't return a Buffer or String
 @ ./src/components/card.vue 10:0-322
 @ ./node_modules/babel-loader/lib!./node_modules/mpvue-loader/lib/selector.js?type=script&index=0!./node_modules/mpvue-config-loader!./src/pages/index.vue
 @ ./src/pages/index.vue
 @ ./node_modules/mpvue-entry/dist/pagesIndex.js

 @ ./src/pages/counter.vue 10:0-373
 @ ./node_modules/mpvue-entry/dist/pagesCounter.js

 @ ./src/packageA/logs.vue 10:0-370
 @ ./node_modules/mpvue-entry/dist/packageALogs.js

**Comment by keycz** [comment]
> 把eslint的相关配置删掉

@viryHd 在项目初始化时没有选择eslint啊

**Comment by viryHd** [comment]
但是在配置项里面，webpack.config里面还有关于eslint的配置，作用于所有的js，你找找。就是在配置loader的那里。现在不方便拉项目截图，你看看把，搜索一下也行

**Comment by keycz** [comment]
@viryHd 大佬 ，在webpack.config里并没有找到eslint相关内容，请问你是在哪里改的？

**Comment by viryHd** [comment]
![snipaste_2019-01-31_09-52-34](https://user-images.githubusercontent.com/42270969/52025072-0b579500-253e-11e9-85ca-0d12c4b81da4.png)

**Comment by keycz** [comment]
> ![snipaste_2019-01-31_09-52-34](https://user-images.githubusercontent.com/42270969/52025072-0b579500-253e-11e9-85ca-0d12c4b81da4.png)
> 这一整段，删掉就好了

这是整个文件的内容，确实没有。
`const path = require('path')
const MpvuePlugin = require('webpack-mpvue-asset-plugin')
const MpvueEntry = require('mpvue-entry')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const utils = require('./utils')
const config = require('../config')
const vueLoaderConfig = require('./vue-loader.conf')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

const entry = MpvueEntry.getEntry('src/app.json')

module.exports = {
  entry,
  target: require('mpvue-webpack-target'),
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
        ? config.build.assetsPublicPath
        : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      '@': resolve('src'),
      vue: 'mpvue'
    },
    symlinks: false,
    aliasFields: ['mpvue', 'weapp', 'browser'],
    mainFields: ['browser', 'module', 'main']
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'mpvue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.vue$/,
        loader: 'mpvue-config-loader',
        exclude: [resolve('src/components')]
      },
      {
        test: /\.js$/,
        include: resolve('src'),
        use: [
          'babel-loader',
          {
            loader: 'mpvue-loader',
            options: {
              checkMPEntry: true
            }
          },
        ]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          name: utils.assetsPath('img/[name].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          name: utils.assetsPath('fonts/[name].[ext]')
        }
      }
    ]
  },
  plugins: [
    new MpvuePlugin(),
    new MpvueEntry(),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: path.resolve(__dirname, '../dist/static'),
        ignore: ['.*']
      }
    ]),
    new CopyWebpackPlugin([
      {
        from: resolve('node_modules/vant-weapp/dist'),
        to: resolve('dist/vant-weapp/dist'),
        ignore: ['.*']
      }
    ])
  ]
}
`

**Comment by keycz** [comment]
算了，不折腾了，老老实实写main.js去

**Comment by F-loat** [comment]
初始化后就报错的话，提供下初始化时的选项

**Comment by spencer1994** [comment]
@F-loat 应该是mpvue-entry不兼容最新的mpvue-loader1.2.0

**Comment by F-loat** [comment]
这个问题今天也遇到了，应该和 mpvue-entry 无关，其他 mpvue 相关的依赖统一更新下就行
