### ISSUE TITLE
main.js为什么会被打包进vendor.js呢

### ISSUE THREAD

**Issue by okflash** [F-loat/mpvue-entry#107]
src/main.js里的内容在npm run dev之后会被打包进common/vendor.js，请问这是个bug吗

**Comment by F-loat** [comment]
main.js 不就是打包入口？。。

**Comment by okflash** [comment]
谢谢回复！但是这样应该不对吧，我在main.js里console.log(123)，打包进了vendor.js。然后有10个页面都调用

**Comment by okflash** [comment]
mpvue的quick-start里，main.js没有被打包进vendor，才是对的吧

**Comment by F-loat** [comment]
src/main.js 会作为模板，你加的 console.log 所有页面的构建入口里都会有，可以加 // app-only 来限制，readme 中有具体说明

**Comment by okflash** [comment]
好的，我看到那一段了，谢谢了！！

**Comment by F-loat** [comment]
没事的，注意看文档
