### ISSUE TITLE
2.0.0-rc.9 保存一次，两次 Compiling...

### ISSUE THREAD

**Issue by a573367014** [F-loat/mpvue-entry#109]
模板是最新的 mpvue/mpvue-quickstart， 不用mpvue-entry打包没这个问题i

**Comment by F-loat** [comment]
示例项目方便提供下不

**Comment by F-loat** [comment]
我需要知道你配置是怎么修改的

**Comment by fengzhiqiang012** [comment]
> 我需要知道你配置是怎么修改的
他应该说的是main.js 保存会俩次  
[mpvue-2.0.zip](https://github.com/F-loat/mpvue-entry/files/2887310/mpvue-2.0.zip)

**Comment by F-loat** [comment]
main.js 的话是正常的，改动后各页面会做一次同步

**Comment by a573367014** [comment]
> main.js 的话是正常的，改动后各页面会做一次同步

是这样的，重新试了下，其他文件不会由此状况
