### ISSUE TITLE
第一次构建总会报错

### ISSUE THREAD

**Issue by hooray** [F-loat/mpvue-entry#111]
运行 `yarn run dev:wx`，执行成功，但微信开发者工具里会报错，错误信息为 `appJSON["pages"][0] 字段需为 string`，需要打开 app.json 文件手动保存一次，让代码再编译一次，才能正常运行。

我看过第一次运行后，`dist/` 目录下编译好的 app.json 文件和源 app.json 一模一样，导致报错，但不知道何解？

**Comment by F-loat** [comment]
使用官方模板的话，把复制 app.json 的配置去掉，readme 中有说明

**Comment by hooray** [comment]
@F-loat 原来如此 😃
