### ISSUE TITLE
分包资源能否放进各子包中而不放在根目录static？

### ISSUE THREAD

**Issue by owen4comes** [F-loat/mpvue-entry#112]
半年前的疑问，现在想再咨询一下~谢谢
目前图片仍然是放在根目录的static下，随着项目的进展，是越来越多了，然后打出来的包也过2M了，所以想看看现在是否已经能将图片等资源放到各自子包里而不算在主包里了o(╥﹏╥)o
#47

**Comment by F-loat** [comment]
static 里的图片直接放线上就行

**Comment by owen4comes** [comment]
好，会尝试一下的~还是盼望着能够在分包里直接搞定~谢谢解答
