### ISSUE TITLE
自定义路由文件夹，出现appJSON 错误

### ISSUE THREAD

**Issue by August2012** [F-loat/mpvue-entry#114]
我想把页面的配置写在JS文件里面，但是编译之后出错，发现编译之后的app.json文件有问题。请问怎么解决？
![image](https://user-images.githubusercontent.com/5556668/56571242-1b3bbe00-65ef-11e9-86e7-13f4539c25d1.png)
![image](https://user-images.githubusercontent.com/5556668/56571279-2db5f780-65ef-11e9-933d-06846ff6eb93.png)
@F-loat

**Comment by August2012** [comment]
貌似不支持啊

**Comment by rni-l** [comment]
你好，我也遇到这个问题，怎么解决的?

**Comment by August2012** [comment]
> 你好，我也遇到这个问题，怎么解决的?

pages 写到 app.json 里面，
config 写到具体页面里面

![image](https://user-images.githubusercontent.com/5556668/59740216-02bbed00-929a-11e9-95c2-da7009fa5de1.png)

![image](https://user-images.githubusercontent.com/5556668/59740248-1ff0bb80-929a-11e9-9fdb-e27a191169bf.png)
