### ISSUE TITLE
使用Quickstart构建项目 运行报 Cannot read property 'exports' of null

### ISSUE THREAD

**Issue by puzzle9** [F-loat/mpvue-entry#116]
2019年04月27日16:46:38
![深度截图_gnome-terminal-server_20190427164421](https://user-images.githubusercontent.com/13518196/56847343-14bd8700-690c-11e9-8059-3d48c3856db4.png)

linux_64

**Comment by puzzle9** [comment]
我本地版本是 v11.14.0 报错
然后用测试机 v8.14.0 正常

**Comment by puzzle9** [comment]
最终换成 node 10.15.3-2 正常

**Comment by kid1412621** [comment]
+1

**Comment by kid1412621** [comment]
❯ node -v
v12.2.0

**Comment by DreamPWJ** [comment]
node12确是不行

**Comment by DreamPWJ** [comment]
建议开发者使用nvm管理node版本，mpvue核心和相关维护不是很积极

**Comment by ahan** [comment]
我也在升级到 node12 后遇到同样报错。

研究了一下，发现错误是来自 `parser/pages.js` 和 `compiler/config.js` 两个文件中  `require(paths.config)` 这句代码。
![WX20190706-194912](https://user-images.githubusercontent.com/654880/60755776-37180300-a027-11e9-8fac-e739b3d13341.png)

谷歌了相关关键词，未找到答案。

不知作者是否有遇到过这种奇怪报错。

**Comment by kid1412621** [comment]
2.0.0 rc.9 还未修复啊

**Comment by F-loat** [comment]
已修复，node12 的 require.cache 可能有些微调，具体原因我后面再跟一下

**Comment by guestccc** [comment]
脑壳痛，看半天才发现是mpvue-entry的bug，哇，好气
