### ISSUE TITLE
运行没问题，但是微信开发工具那边报错了

### ISSUE THREAD

**Issue by apony** [F-loat/mpvue-entry#118]
![1562605287(1)](https://user-images.githubusercontent.com/33817895/60828504-1d241f00-a1e5-11e9-91d9-93c2bb8a5be1.jpg)
老哥，这是什么回事啊？而且，页面一片空白。
![1562605414(1)](https://user-images.githubusercontent.com/33817895/60828658-8c9a0e80-a1e5-11e9-92e4-2e694b14e72e.jpg)
![1562605358(1)](https://user-images.githubusercontent.com/33817895/60828659-8dcb3b80-a1e5-11e9-9707-b18c83368fdd.jpg)

**Comment by apony** [comment]
webpack.base.conf配置应该是没问题的。

**Comment by F-loat** [comment]
用的是哪个版本，配置可以和我提供的模板做下对比
