### ISSUE TITLE
pages/count/index.js 出现脚本错误或者未正确调用 Page()

### ISSUE THREAD

**Issue by hotlove** [F-loat/mpvue-entry#121]
没有使用F-loat模板，从官网下载得mpvue2.0 然后引入mpvue-entry, mpvue-router-patch刚开始配置成功了引入第三方组件也是没问题得，但是第二天再次得打开得时候就一直报这个错误
![1](https://user-images.githubusercontent.com/19171186/61924908-76899d80-af9c-11e9-89c4-859503e5ce73.png)
![2](https://user-images.githubusercontent.com/19171186/61924909-78536100-af9c-11e9-8847-fbab3fdbb748.png)
![3](https://user-images.githubusercontent.com/19171186/61924910-79848e00-af9c-11e9-8742-b2c96cff0b82.png)
![4](https://user-images.githubusercontent.com/19171186/61924911-7ab5bb00-af9c-11e9-9915-c5d9d6dbeab5.png)
![5](https://user-images.githubusercontent.com/19171186/61924913-7be6e800-af9c-11e9-8078-657cb60f165c.png)

**Comment by F-loat** [comment]
用 2.x 版本的 mpvu-entry 试下

**Comment by hotlove** [comment]
还是不行
![1](https://user-images.githubusercontent.com/19171186/61930329-f40ad900-afaf-11e9-95a8-0dbcd9c9257c.png)
![2](https://user-images.githubusercontent.com/19171186/61930337-fa00ba00-afaf-11e9-9515-ebc18dbf04ef.png)
![3](https://user-images.githubusercontent.com/19171186/61930339-fbca7d80-afaf-11e9-95d9-fb38564138f2.png)
![4](https://user-images.githubusercontent.com/19171186/61930342-fcfbaa80-afaf-11e9-99ad-e02459a42368.png)
![5](https://user-images.githubusercontent.com/19171186/61930343-fec56e00-afaf-11e9-8011-f1b839752b00.png)

**Comment by F-loat** [comment]
dist 目录手动清空下，然后开发工具重新导入试试

**Comment by hotlove** [comment]
重新改了webpack.base.config.js 和main.js现在好了

**Comment by F-loat** [comment]
想起来了这个是不是没删官方复制 app.json 的配置
