### ISSUE TITLE
routes配置文件缓存问题

### ISSUE THREAD

**Issue by ltinyho** [F-loat/mpvue-entry#13]
test.routes.js
```
const testRoutes = require('./test/index');

module.exports = testRoutes;

```
我想通过其他配置文件导入，但是会把`test.routes.js`文件缓存起来，第二次路径肯定不对的，可以加个配置项，是否缓存吗

**Comment by ltinyho** [comment]
这个是为了打包成多个不同的小程序，但路由配置有一些不同，不想copy路由配置

**Comment by F-loat** [comment]
你可以试下在 require 前先清除一次缓存 require.cache[path] = null;

**Comment by F-loat** [comment]
emm你是热更有问题还是启动就有问题，你这种用法好像目前没法热更

**Comment by F-loat** [comment]
pages 参数支持数组的格式能满足你的需求不，可以传入多个页面配置文件这样

**Comment by ltinyho** [comment]
我现在是启动和打包有问题，缓存造成二次启动不了，路径对不上了，我是想自定义，动态生成route配置。

**Comment by ltinyho** [comment]
缓存现在是把router.js文件里面的内容写到备份js文件里面，但是比如这种写法
router配置文件，从相对路径引入其他的js配置,合并路由配置
```
const routes= required("./test.routes.js")
```
再次执行的时候，在mpvue-entry取路径是取不到，文件不存在的

**Comment by F-loat** [comment]
嗯，懂了，我先加个加个禁用缓存的配置项

**Comment by F-loat** [comment]
对了，你试下 `const routes= required("@/test.routes.js")`，这样应该也可以

**Comment by F-loat** [comment]
你更新 0.4.0 版本试下，readme 里有使用说明

**Comment by ltinyho** [comment]
好的，谢谢

**Comment by F-loat** [comment]
1.1.2 这个版本调整了备份方式，应该开启缓存也没问题了

**Comment by ltinyho** [comment]
好的，我用一下
