### ISSUE TITLE
大神，用了这插件原来的MpvuePlugin不需要了吗

### ISSUE THREAD

**Issue by yzw2017** [F-loat/mpvue-entry#17]
在webpack.base.conf.js里
plugin: [new MpvueEntry()]  代替了原来的 MpvuePlugin
我试过 不换 项目根本启动不了 替换了才能正常使用
这样换了一个plugin 对项目最终打包上线 不会有影响吧？

**Comment by F-loat** [comment]
两个插件没关系的，应该同时使用更好一点

**Comment by F-loat** [comment]
``` js
plugin: [
  new MpvueEntry(),
  new MpvuePlugin()
]
```
