### ISSUE TITLE
无法正确查找文件

### ISSUE THREAD

**Issue by cztflove** [F-loat/mpvue-entry#18]
按照文档配置好后运行会提示以下错误
These dependencies were not found:
* @/pages/index/main in ./node_modules/mpvue-entry/dist/pagesIndexMain.js
* @/pages/logs/main in ./node_modules/mpvue-entry/dist/pagesLogsMain.js

pages下的main.js不是应该删除掉由mpvue-entry生成的吗？

**Comment by F-loat** [comment]
``` js
// pages.js
module.exports = [
  {
    path: '/pages/news/list', // 页面路径，同时是 vue 文件相对于 src 的路径
    config: { // 页面配置，即 page.json 的内容
      navigationBarTitleText: '文章列表',
      enablePullDownRefresh: true
    }
  }
]
```

**Comment by F-loat** [comment]
`path` 属性不要保留 `main`，`/pages/news/list` 代表的是 `src/pages/news/list.vue` 这个文件

**Comment by cztflove** [comment]
感谢，已解决
