### ISSUE TITLE
出现脚本错误或者未正确调用 Page()

### ISSUE THREAD

**Issue by kankungyip** [F-loat/mpvue-entry#2]
src/main.js 文件中如果有 `App.mpType = 'app'`，将导致编译后的文件出现“出现脚本错误或者未正确调用 Page()”

需要在处理模版文件时，替换为`App.mpType = 'page'`，才能正常使用。

**Comment by F-loat** [comment]
嗯，这个我尽快处理下，可以暂时把 mpType 属性放在 App.vue 文件中解决

**Comment by F-loat** [comment]
已修复
