### ISSUE TITLE
经常出现 WAIT  Compiling... 

### ISSUE THREAD

**Issue by qbob** [F-loat/mpvue-entry#20]
修改页面的时候经常出现WAIT  Compiling... 重新编译又好了，是不是跟插件有关？

![image](https://user-images.githubusercontent.com/1908445/40346583-e132a5ca-5dcf-11e8-8164-42f58fab99d6.png)

**Comment by F-loat** [comment]
一直等待不继续编译了吗，这个还没遇到过

**Comment by qbob** [comment]
是的，编辑页面和配置文件都没有反应，重新编译恢复正常

**Comment by F-loat** [comment]
一般是什么情况下会出现这个问题，目前这个插件的代码应该不会导致这样

**Comment by F-loat** [comment]
优化了下配置文件的更新时机，可以更新下试试
