### ISSUE TITLE
can not support life hook function config

### ISSUE THREAD

**Issue by lemonpigpig** [F-loat/mpvue-entry#21]
module.exports = [
  {
    path: '/pages/index/index',
    name: 'Index',
    config: {
      navigationBarTitleText: '首页',
      enablePullDownRefresh: true,
      onLoad: function () {
        console.log('onLoad')
      }
    }
  }
]y
the onLoad hook function is ignored in the output by the JSON.stringify().so this is not for life hook confg?

**Comment by F-loat** [comment]
这里是页面配置，相当于小程序的 json 文件，生命周期函数是要写在 js 文件里的，也就是 mpvue 里的 vue 文件
