### ISSUE TITLE
整合第三方ui

### ISSUE THREAD

**Issue by lemonpigpig** [F-loat/mpvue-entry#22]
引入weui的时候报路径错误，想问一下正确的引入方式
![2018-05-28 11 51 45](https://user-images.githubusercontent.com/17818782/40596481-bd4cf1e0-626d-11e8-9fd8-f60942c9a68a.png)
![2018-05-28 11 51 51](https://user-images.githubusercontent.com/17818782/40596482-bd85759c-626d-11e8-98c8-b9241c9a6a23.png)

**Comment by spencer1994** [comment]
mpvue-entry产生的文件是在node_modules/mpvue-entry/dist里的，不能用相对路径。
一般来说用@来引用就可以了，如果你没放在src里，有三种方案尝试。
1. static的话，你试试用绝对路径
2.放src用@来引用
3.webpack里加一个别称来引用

**Comment by lemonpigpig** [comment]
谢谢

**Comment by F-loat** [comment]
还有就是样式文件可以在 app.vue 里引入
