### ISSUE TITLE
跟新后编译通不过

### ISSUE THREAD

**Issue by lemonpigpig** [F-loat/mpvue-entry#23]
![2018-05-28 1 11 55](https://user-images.githubusercontent.com/17818782/40598178-cd3f3fd0-6278-11e8-933f-f419dca3b26f.png)

**Comment by F-loat** [comment]
配置有改吗

**Comment by lemonpigpig** [comment]
![2018-05-28 1 20 36](https://user-images.githubusercontent.com/17818782/40598494-94078f40-627a-11e8-93e1-db016c53ddcd.png)
![2018-05-28 1 21 41](https://user-images.githubusercontent.com/17818782/40598492-93da2fc8-627a-11e8-9154-27930f32c7ef.png)
![2018-05-28 1 22 45](https://user-images.githubusercontent.com/17818782/40598491-93ac65e8-627a-11e8-9150-4a821b675ff5.png)

**Comment by F-loat** [comment]
你的 entry 是怎么定义的

**Comment by F-loat** [comment]
https://github.com/F-loat/mpvue-quickstart 可以直接使用这个模板生成项目

**Comment by F-loat** [comment]
你开调试默认看下是哪儿报的错？

**Comment by lemonpigpig** [comment]
用了模板生成报同样的错误，请问node的版本有要求吗

**Comment by F-loat** [comment]
node 版本会有要求，可能 class 是用的语法里最新的？

**Comment by F-loat** [comment]
你编辑器用的是 vscode 或者 webstorm 吗，调试下看看

**Comment by lemonpigpig** [comment]
我的node版本问题6.x.x太低现在好了，另外怎么调试，妹纸有点菜呜呜

**Comment by F-loat** [comment]
https://code.visualstudio.com/Docs/editor/debugging
debug 模式遇到为捕获的错误会自动定位到

**Comment by F-loat** [comment]
另外有看到说你这个错误是新版 prettier 导致的，装回旧版即可，晚点我看下新版是要改什么配置

``` bash
npm i -D prettier@1.12.0
```
