### ISSUE TITLE
BUG：部分页面报错 invoking page() in async task 

### ISSUE THREAD

**Issue by zaxlct** [F-loat/mpvue-entry#24]
假设有 10 个 page，其中有两个 page ，开发者工具上正常，iOS 9 和 部分低端安卓手机报这个错误

    "mpvue": "^1.0.12",
     mpvue-entry 最新版

**Comment by F-loat** [comment]
不觉得是这个库的问题，这个库不会直接影响打包结果的

**Comment by zaxlct** [comment]
@F-loat 去掉了  mpvue-entry ，其中一个 page  问题解决了，还有一个 page 没解决。应该不是这个库的问题

**Comment by zaxlct** [comment]
好的，谢谢

**Comment by zaxlct** [comment]
Do not have handleProxy handler in current page: pages/recharge/deposit/main. Please make sure that handleProxy handler has been defined in pages/recharge/deposit/main, or pages/recharge/deposit/main has been added into app.json


请教下，这样的错误遇到过吗
@F-loat

**Comment by F-loat** [comment]
绑定事件用 @ 不要用 bind，这个搜 issue 应该有很多
