### ISSUE TITLE
在main.js中使用usingComponents导入的原生组件,在页面中引用为空白

### ISSUE THREAD

**Issue by kalooboy** [F-loat/mpvue-entry#25]
![image](https://user-images.githubusercontent.com/23286421/40764627-5a91e3c8-64dc-11e8-927c-16a36c61798d.png)
这个是官方mpvue中的引入方式,表现正常

![image](https://user-images.githubusercontent.com/23286421/40764652-762eecca-64dc-11e8-9f1e-ef3aa3817302.png)
这个是在mpvue-entry的main.js中的引入方式,实际页面引用的时候无效,表现为空白元素

**Comment by F-loat** [comment]
页面的配置你应该写在 pages.js 里该页面对应的 config 属性中

**Comment by kalooboy** [comment]
已解决,刚刚确实试去了,正准备关闭该条,作者就回复了,回复效率棒棒的啊!

**Comment by cdll** [comment]
@F-loat 抱歉麻烦问一下, 我现在是有个原生项目重构为mpvue的, 暂时页面都还是原生的, 第一步现在是脚手架替换为mpvue, 现在遇到一个问题就是我原项目中移进main.js的``config.pages``是字符串数组, 然后在mpvueEntry用到的pages.js中, 配置的是一个空数组(因为页面太多了, config就先不一个一个搬过来了, 所以原来每个页面都有其原对应的``.json``配置文件), 现在遇到的问题就是貌似pages里的值完全覆盖了main里的``config.pages``, 这块想问一下有优化的空间么?

**Comment by cdll** [comment]
快速解决方案现在我能做到的就是 ``pages.js`` 中每个path的config都使用 ``require(<path>.json)`` 来省去手动拷贝搬迁, 但是也还是要全写完吖心累求理解~ T_T

**Comment by cdll** [comment]
@F-loat 字符串数组的方式, 没法标记  ``native: true`` ...

**Comment by cdll** [comment]
木事儿了, 昨儿晚通宵写完了抹耶我自己都害怕...😨
