### ISSUE TITLE
MpvueEntry.genEntry is not a function

### ISSUE THREAD

**Issue by Aibokalv** [F-loat/mpvue-entry#26]
`var MpvueEntry = require("mpvue-entry");`
...
`module.exports = {
  entry: MpvueEntry.genEntry("src/router/routes.js"),`

`TypeError: MpvueEntry.genEntry is not a function
    at Object.<anonymous> (/My/suishoupai/build/webpack.base.conf.js:14:21)`

package.json
` "mpvue-entry": "^1.2.4",`

我是按照simple里配置来的  不知道为什么总报这个错

**Comment by F-loat** [comment]
`MpvueEntry.getEntry('src/pages.js')`
