### ISSUE TITLE
更新最新版无法指定首页

### ISSUE THREAD

**Issue by zhichaoGuo** [F-loat/mpvue-entry#30]
### main.js
![image](https://user-images.githubusercontent.com/12584373/41575998-9ab0514e-73b7-11e8-8c98-b49d4cdc1bdb.png)
### webpack.base.conf.js
![image](https://user-images.githubusercontent.com/12584373/41576024-b18cbb8c-73b7-11e8-982a-30eb2bfdee87.png)
### dist/app.json
![image](https://user-images.githubusercontent.com/12584373/41576036-bf4aeaf0-73b7-11e8-83a6-d3cc27ae70bf.png)

**Comment by F-loat** [comment]
暂时不准备支持 main.js 里指定 https://github.com/F-loat/mpvue-entry#tips

**Comment by F-loat** [comment]
正则匹配下 main.js 里指定的首页倒也不是太麻烦，我最近有空加一下

**Comment by zhichaoGuo** [comment]
![image](https://user-images.githubusercontent.com/12584373/41579751-cf9ccc58-73ca-11e8-8486-4d15bc0fb1c5.png)
看来我只能临时配置一下

**Comment by F-loat** [comment]
可以安装 github 上的版本试下，没什么问题我再发布

``` bash
npm i -D https://github.com/F-loat/mpvue-entry.git
```

**Comment by zhichaoGuo** [comment]
试了一下 没问题的

**Comment by zhichaoGuo** [comment]
main.js
![image](https://user-images.githubusercontent.com/12584373/41839002-9f45ca40-7894-11e8-9fdb-a2580dbafbbd.png)
这里的正则匹配始终是匹配最后一个， 即使我已经注释了，正则匹配规则可能需要改一下

**Comment by F-loat** [comment]
开发调试还是建议你们用开发工具的配置，晚点我优化下
