### ISSUE TITLE
可通过 native 属性指定页面为原生开发，不做编译处理

### ISSUE THREAD

**Issue by longdan** [F-loat/mpvue-entry#31]
这个不起作用，页面还是被编译了

**Comment by F-loat** [comment]
版本？

**Comment by longdan** [comment]
我升到1.7.2  没把目录给拷到dist的pages去呢？但app.json的pages数组里确加进去了

**Comment by F-loat** [comment]
拷贝不是这个库处理的事情

**Comment by F-loat** [comment]
加这个功能的话，效果是把 `pages/news/list.json` `pages/news/list.js` `pages/news/list.wxml` 和 `pages/news/list.wxss` 这几个文件拷贝到 `dist/pages/news` 目录下？

**Comment by F-loat** [comment]
虽然也可以做，但是感觉没什么必要，建议把原生页面集中放在一个文件夹里，然后通过 webpack 的插件进行拷贝

**Comment by longdan** [comment]
哦!我以为是有copy能力，那我自己在webpack里处理下
