### ISSUE TITLE
如何指定 tabbar 页面路径？

### ISSUE THREAD

**Issue by Vultur** [F-loat/mpvue-entry#32]
// pages.js

```
module.exports = [
  {
    path: 'pages/index/index'
  }
]
```

// main.js

```
tabBar: {
      list: [
        {
          pagePath: 'pages/index/index'
        },
        {
          pagePath: 'pages/index/index'
        }
      ]
    }
```

_pagePath_ "pages/index/index" 需在 pages 数组中

**Comment by F-loat** [comment]
和普通页面没区别的，是不是你两个 tab 路径一致了的问题

**Comment by Vultur** [comment]
@F-loat 不是重复的问题。没理解，和普通页面没区别是指在 main.js 配置 tabBar 选项 还是 pages.js 中配置？

**Comment by F-loat** [comment]
在 pages.js 中和其他页面没区别，在 main.js 中和其他项目没区别

**Comment by F-loat** [comment]
可以参考这个项目 https://github.com/F-loat/ithome-lite

**Comment by Vultur** [comment]
解决，是没有区别！
