### ISSUE TITLE
pages.js能够引入其他js组成最终的路由列表吗

### ISSUE THREAD

**Issue by xlkit456852** [F-loat/mpvue-entry#36]
项目有很多的路由，不想把全部路由写在同一个pages.js，想在其他目录分了模块js，再在pages.js引入这些模块js，最后组装成全部路由列表，但是尝试过后报以下错误，pages.js是不是不支持这样的引入方式？

![image](https://user-images.githubusercontent.com/7323450/42019673-4caa983c-7ae8-11e8-8af6-d4d94c75b4ef.png)

pages1.js代码：
import routes from './router/routes';
module.exports = routes;

router目录：
![_20180628153441](https://user-images.githubusercontent.com/7323450/42019953-11eb549c-7ae9-11e8-87fe-b1ff1b3d4a6a.png)

**Comment by F-loat** [comment]
支持的，但是这个文件是在 node 环境下直接执行的，所以要用 require

**Comment by xlkit456852** [comment]
太棒了！感谢作者分享这个插件和耐心回答，这个插件对我非常有用处！
