### ISSUE TITLE
希望可以兼容下TS版

### ISSUE THREAD

**Issue by bigmeow** [F-loat/mpvue-entry#38]

**Comment by bigmeow** [comment]
单文件组件 配合 ts
https://github.com/WingGao/mpvue-ts-demo

**Comment by F-loat** [comment]
具体会有什么差异呢

**Comment by bigmeow** [comment]
上面发的那个仓库脚手架已经实现了可以在项目里写typescript,不过还是需要一个页面对应一个文件夹，希望可以使用mpvue-entry改成集中式配置的；
mpvue-entry是自动生成main.js， 要兼容TS的话，可能需要这边处理下，先自动生成main.ts，然后交给脚手架的ts-loader来处理，目前我也在本地尝试修改mpvue-entry，不过还没整出来

**Comment by F-loat** [comment]
https://github.com/WingGao/mpvue-ts-demo/blob/dev/src/pages/counter/main.ts
这个文件看起来没什么特别的啊，直接把输出的文件后缀改为 .ts，然后模板自定义下不可以吗

**Comment by bigmeow** [comment]
你看下首页src下面的main.ts  里面有相关的TS代码

**Comment by F-loat** [comment]
template 属性指定为另一个文件就行，或者用 // app-only 标记一下

**Comment by bigmeow** [comment]
不过目前main.ts里面的东西和  页面需要的差别太大了, 试了你说的 // app-only 和另外一个标记，
满足不了需求，除非能将主页面的main.ts  和  其他子页面的需要的模版区分开，就能实现，这个需求我看和 https://github.com/F-loat/mpvue-entry/issues/27 是一样的。
main.ts里需要的东西：
```typescript
import { Component, Emit, Inject, Model, Prop, Provide, Vue, Watch } from 'vue-property-decorator';
import { VueConstructor } from "vue";

interface IMpVue extends VueConstructor {
  mpType: string
}

// 添加小程序hooks http://mpvue.com/mpvue/#_4
Component.registerHooks([
  // app
  'onLaunch', // 初始化
  'onShow', // 当小程序启动，或从后台进入前台显示
  'onHide', // 当小程序从前台进入后台
  // pages
  'onLoad', // 监听页面加载
  'onShow', // 监听页面显示
  'onReady', // 监听页面初次渲染完成
  'onHide', // 监听页面隐藏
  'onUnload', // 监听页面卸载
  'onPullDownRefresh', // 监听用户下拉动作
  'onReachBottom', // 页面上拉触底事件的处理函数
  'onShareAppMessage', // 用户点击右上角分享
  'onPageScroll', // 页面滚动
  'onTabItemTap', //当前是 tab 页时， 点击 tab 时触发 （mpvue 0.0.16 支持）
])

Vue.config.productionTip = false
// 在这个地方引入是为了registerHooks先执行，这里不能用import引入，否则app.vue的生命周期函数不能执行
const MyApp = require('./App.vue').default as IMpVue



const app = new Vue(MyApp)
```

页面模板需要的东西：
```js

import Vue from 'vue'
import App from '@/App'

const app = new Vue(App)
app.$mount()

export default {
  // 这个字段走 app.json
  config: {
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  }
}
``

我看你的插件是源码是替换模板中的代码：
```js
xxx.replace(/import App from .*/, `import App from '@/${page.path}'`)
```

可以看到，main.ts里都不能用import来引入app.vue了 ，你的插件也没法替换了。

**Comment by F-loat** [comment]
嗯，没在 vue 里用过 ts，重新定义一个模板目前可行吗，靠正则处理这个好像比较复杂，，后面改用 babel 的话我试试

**Comment by bigmeow** [comment]
本来想在webpack.base.config.js里把main.ts 写在entry里，和你的 MpvueEntry插件获取到的entry Object.asign合并的，不过发现MpvueEntry 返回的是一个promise 方法 ，那就只能在你的方法里改了

**Comment by bigmeow** [comment]
只要处理好 main.ts 和 子页面的 main.js 区别就行了 ，可行的

**Comment by F-loat** [comment]
对，app 的处理目前是和 template 那个属性绑定的。。可以加个配置项 main，app 对应的入口用 main || template 这样

**Comment by F-loat** [comment]
@bigmeow 多加了个属性了

**Comment by bigmeow** [comment]
这么快。。。我还想着晚上回去了提个pull request
👍

**Comment by F-loat** [comment]
😂刚好在用电脑就顺便改了，那你之后测试看看

**Comment by bigmeow** [comment]
已经集成进来，测试通过，不过另外一个仓库要稍微做点修改：https://github.com/WingGao/mpvue-ts-demo/issues/1
再次感谢，写几个页面确认无误没有大问题后我在将集成的配置贡献出来

**Comment by yaosong2100** [comment]
@bigmeow  集成的配置可以共享下？
