### ISSUE TITLE
config能否在page.vue文件中配置

### ISSUE THREAD

**Issue by maimake** [F-loat/mpvue-entry#39]
每个页面的config应该呆在page才适合，里面的配置和page息息相关。如果放在pages.js里，很容易会忘记掉，尤其是如果有使用usingComponents的时候

**Comment by F-loat** [comment]
2.x 版本会考虑支持这种方式，主要是配置的热更新要考虑好怎么处理，不需要热更新的话，目前可以这个脚本自动读取 vue 文件中的配置，然后生成 pages.js 文件

**Comment by F-loat** [comment]
#33
