### ISSUE TITLE
换成这个架子之后，components的里click绑定报错

### ISSUE THREAD

**Issue by hjdshu** [F-loat/mpvue-entry#44]
事件绑定失败？  

VM395:1 thirdScriptError
Cannot read property 'sendEvent' of undefined;at pages/index/index page handleProxy function
TypeError: Cannot read property 'sendEvent' of undefined

**Comment by F-loat** [comment]
这个库只是自动生成了 webpack 的入口文件，不会对其他环节产生影响，可以自己查看下 node_modules/mpvue-entry/dist 目录下的文件排查问题
