### ISSUE TITLE
webpack配置rules中的 test: /\.vue$/ 使用多个loader后webpack报错

### ISSUE THREAD

**Issue by js5323** [F-loat/mpvue-entry#46]
问题：
webpack配置rules中的 `test: /\.vue$/`  use多个loader后webpack报错：
``
没有找到空闲端口，请打开任务管理器杀死进程端口再试 Error: No loader specified
``

目前看到的原因是/lib/index.js 中 line 47：
`const { loader } = compiler.options.module.rules.find(rule => rule.test.source === '\\.vue$') || {};`
如果rules中是使用多个loader，这里获取到的loader是undefined的。。。

**Comment by F-loat** [comment]
你把 loader 的配置贴一下

**Comment by js5323** [comment]
Hello，rules配置如下：
````rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'mpvue-loader',
            options: vueLoaderConfig
          },
          {
            loader: 'other-loader',
            options: { ... }
          },
          ...
        ]
      }
````
