### ISSUE TITLE
请问分包资源放在哪里和如何加载？

### ISSUE THREAD

**Issue by xlkit456852** [F-loat/mpvue-entry#47]
目前所有页面的图片都是放到根目录下的/static里面的，里面包括分包的图片，所以占用了主包的大小了，导致主包超出了2M限制，现在想把分包的资源放回到分包里面去，我尝试过以下操作：

分包1目录：/src/module/test1
```
pages.js:
{
        path: 'module/test1/index',
        subPackage: true,
        config: { // 页面配置，即 page.json 的内容，可选
            navigationBarTitleText: '品牌榜',
            enablePullDownRefresh: false
        }
    },
```
然后我将分包1的图片资源放在/src/module/test1/assets/images中，但是打包出来后图片都不见了。看过dist里面的module，原来是assets文件夹没有了，请问这个分包资源应该放到哪里让分包加载呢？

**Comment by F-loat** [comment]
这部分应该还没处理吧，用相对路径引用最后也还是统一复制到一起的，官方最近再处理分包的问题了，可以关注下，这个模板也只是一个临时方案

**Comment by xlkit456852** [comment]
好的，那我先暂时减小图片的大小吧！谢了！
