### ISSUE TITLE
导入css、less后报错

### ISSUE THREAD

**Issue by jpdan** [F-loat/mpvue-entry#50]
![e s q9o w848ukmy _ g](https://user-images.githubusercontent.com/3361732/42978893-0af88f4a-8c02-11e8-8f5e-eb78f3d0fe32.png)
![image](https://user-images.githubusercontent.com/3361732/42978902-143f8fcc-8c02-11e8-9874-02c8dc7dca7b.png)
一导入就报错，去掉就没事，而且注释后热启动还是报错，必须重启
但是在App.vue中style下导入时可以的

**Comment by F-loat** [comment]
最新版应该支持这种写法了，旧版可以用 `@/xxx` 这种方式引入，或者通过 `// app-only` 做下标识

**Comment by jpdan** [comment]
mpvue-entry@1.4.4，就是最新版了，@是可以的，相对路径并不阔以

**Comment by F-loat** [comment]
相对路径应该会转为绝对路径的，我明天再测下

**Comment by F-loat** [comment]
@jpdan 修复了，之前确实只匹配了 `import xxx from './xxx'` 的语句，v1.4.7
