### ISSUE TITLE
win10下页面中js和css路径获取有问题

### ISSUE THREAD

**Issue by mrichie** [F-loat/mpvue-entry#51]
问题描述：
今天为了实践下分包加载的特性，先升级下loader版本
```javascript
-    "mpvue-entry": "^1.2.0",
-    "mpvue-loader": "1.0.12",
+    "mpvue-entry": "^1.4.0",
+    "@f-loat/mpvue-loader": "^1.0.0",
```
然后mac下编译工作正常，windows下编译正常，但运行时提示每个页面中引入的js和css路径都找不到了

比如某个页面的main.js中，头部包含如下引用代码：```require("..\..\..\..\manifest\js\main.js")```，win下变成了反斜杠

在开发者工具控制台提示“找不到文件......manifestjsmain.js”，提示错误中连反斜杠都没有了

**Comment by F-loat** [comment]
https://github.com/F-loat/mpvue-quickstart 这个初始化之后的项目就有问题吗？我电脑也是 win10 的啊

**Comment by F-loat** [comment]
还有问题的话，请进一步反馈
