### ISSUE TITLE
升级到最新版之后提示错误

### ISSUE THREAD

**Issue by HADB** [F-loat/mpvue-entry#52]
```
if (compilation.assets['app.json'].emitted) {
                                       ^

TypeError: Cannot read property 'emitted' of undefined
```

**Comment by F-loat** [comment]
之前使用的是哪个版本？

**Comment by HADB** [comment]
"mpvue": "^1.0.11"
"mpvue-entry": "^1.2.2"
"mpvue-loader": "^1.0.13"

全部升级到最新版之后，出现上述错误，dist目录中未生成app.json文件。
将版本回退至上述版本，重新编译，就没问题。

**Comment by F-loat** [comment]
mpvue-loader 也更到最新版了吗，可能还不兼容，你单独更新 mpvue-entry 试下

**Comment by HADB** [comment]
单独升级mpvue-entry到1.4.4，没有问题。看来是跟最新的mpvue-loader有些兼容性问题。

**Comment by F-loat** [comment]
v1.4.5

**Comment by F-loat** [comment]
新的模板我后面同步更新下
