### ISSUE TITLE
项目运行无法生成json文件 页面标题不显示

### ISSUE THREAD

**Issue by lgb531** [F-loat/mpvue-entry#53]
![image](https://user-images.githubusercontent.com/26864739/43133066-34d21bb2-8f70-11e8-8554-163a9e64ad59.png)
如图，使用npm run dev 命令后，这个json文件并没有生成，然后小程序顶部标题不会变，手动复制老项目里面的json文件才行

pages.js截图
![image](https://user-images.githubusercontent.com/26864739/43133255-ccc43f36-8f70-11e8-97ae-7da448db9ca1.png)

目前依赖版本
`"mpvue-loader": "^1.1.2-rc.4"`
`"webpack-mpvue-asset-plugin": "~0.1.0"`

**Comment by F-loat** [comment]
先等等看官方最后是怎么处理这个问题的

**Comment by lgb531** [comment]
好的

**Comment by weiyunpeng** [comment]
同问

**Comment by F-loat** [comment]
详细说一下，目前 mpvue-entry 是通过生成指定格式的入口文件供 mpvue-loader 生成 json 文件的

mpvue-loader@1.1.x 似乎把页面配置分离到 main.json 文件中了，通过插件进行复制

最后确实是这样处理了的话，我这边预计会改为直接生成 json 文件，使用方式不需要改动

**Comment by charleslo1** [comment]
确实没生成页面 json 文件

**Comment by F-loat** [comment]
项目模板的主分支回退了下，暂时使用旧版 loader，后面同步更新下
https://github.com/F-loat/mpvue-quickstart

**Comment by weiyunpeng** [comment]
有结论了没？

**Comment by F-loat** [comment]
等官方模板的 mpvue-loader 更新之后再定

**Comment by cduyzh** [comment]
@F-loat 还没更新吗

**Comment by cduyzh** [comment]
@charleslo1 @weiyunpeng @lgb531 
#58 可以看下这个

**Comment by F-loat** [comment]
有个 pr 了已经，这两天应该会更新

**Comment by luyixin** [comment]
感谢，帮了大忙了

**Comment by gaoxiaosong1113** [comment]
请问这个问题解决了么？

**Comment by luckyyyyy** [comment]
@F-loat 最近升级到1.1.x了 是时候更新一下了 现在自己修改可以 但是还是希望方便其他人npm 更新一下

**Comment by Rem486** [comment]
按照 [https://github.com/F-loat/mpvue-entry/issues/58](url) 修改了，生成了各个页面的 x.json。
没有生成app.json 呢

**Comment by F-loat** [comment]
#59
