### ISSUE TITLE
添加了新的组件，不能热更新？每次都要重新编译

### ISSUE THREAD

**Issue by zhangyt93** [F-loat/mpvue-entry#55]
RT
添加了新的组件，不能热更新？每次都要重新编译

**Comment by F-loat** [comment]
原生组件还是什么，不涉及入口文件 (main.js) 的问题应该和 mpvue-entry 无关

**Comment by zhangyt93** [comment]
vue组件，用的是    "@f-loat/mpvue-loader": "^1.0.0",

**Comment by zhangyt93** [comment]
好奇怪 如果页面只有一个组件 就能更新， 但是如果页面已经存在其他组件就不会更新

**Comment by F-loat** [comment]
可以试下官方模板，有同样问题的话建议到 mpvue 的仓库反馈
