### ISSUE TITLE
pages.js里面的config配置不生效

### ISSUE THREAD

**Issue by javanf** [F-loat/mpvue-entry#63]
module.exports = [{
  path: 'pages/user/login'
},{
  path: 'pages/user/register',
  config: {
    navigationBarTitleText: '注册'
  }
},{
  path: 'pages/index/index'
}]
这里的config配置没有生效，请教？？？

**Comment by F-loat** [comment]
使用的是 1.1.0 以上版本的 mpvue-loader 的吗

**Comment by javanf** [comment]
恩，是的。目前是1.1.2

**Comment by javanf** [comment]
试了一下1.1.0和1.0.15同样也不行

**Comment by F-loat** [comment]
试下这个模板 https://github.com/F-loat/mpvue-quickstart
