### ISSUE TITLE
能否支持拆分vendor,单个最大体积500kb

### ISSUE THREAD

**Issue by cduyzh** [F-loat/mpvue-entry#65]
## 原因
如果按目前的打包流程来，当vendor大于500kb小程序不会转es5,但是vendor里引用的node_modules里用到了一些es6及以上用法没有转换为es5（例如const）,这样导致了小程序在收的低系统版本会报错，单独把vendor手动转es5就可以解决，但这样长期发包起来不方便

**Comment by F-loat** [comment]
这个应该需要 mpvue-loader 配合来做吧

**Comment by cduyzh** [comment]
@F-loat 能提供下解决思路吗？

**Comment by F-loat** [comment]
你如果只是想转换 es6 代码的话，改下 webpack 配置就可以啊
