### ISSUE TITLE
无法生成app.json

### ISSUE THREAD

**Issue by kokororin** [F-loat/mpvue-entry#66]
使用了最新的模板 F-loat/mpvue-quickstart 和 mpvue-entry
最终的dist目录中没有app.json

把https://github.com/F-loat/mpvue-entry/blob/master/lib/compiler.js#L88-L91
改为
```js
  const configPath = path.join(paths.dist, 'app.json');
  fs.writeFileSync(configPath, JSON.stringify(app, null, '  '));
```
后可行
是不是windows的关系？

**Comment by F-loat** [comment]
使用了 mkdirp 这个模块保证文件生成目录存在，应该不会有兼容性问题吧，windows 我得晚上回去了测下

**Comment by F-loat** [comment]
加个 catch 看看有错误没

**Comment by kokororin** [comment]
谢谢，测试了一下也不是系统的问题，在`makeDir`方法里打印`err`也没有错误，
暂时先靠fork一份解决了:smile:

**Comment by F-loat** [comment]
没有错误可能是因为没把错误抛出来。。你改下 makeDir 这个函数看看
