### ISSUE TITLE
这个是什么问题？

### ISSUE THREAD

**Issue by cooluid** [F-loat/mpvue-entry#7]
D:\vue\xcool\node_modules\mpvue-entry\index.js:1
(function (exports, require, module, __filename, __dirname) { import Vue from 'vue'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\vue\xcool\build\webpack.base.conf.js:3:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xcool@0.0.1 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xcool@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

改了main.js里面的index入口，或者其他文件，每次都要去node_modules下面删掉mpvue-entry然后重新安装才能编译

**Comment by F-loat** [comment]
你 node 版本是多少，另外

> 改了main.js里面的index入口，或者其他文件

这个没太懂

**Comment by cooluid** [comment]
// 这个字段走 app.json
  config: {
    pages: [
      'pages/index/index'
    ], // Will be filled in webpack
改'pages/index/index'这个为其他的页面，就必定会报上面的那个错误，
node  v8.9.4

**Comment by F-loat** [comment]
pages 内的页面需要在 pages.js 里定义过才行

**Comment by cooluid** [comment]
这个文件在哪里的， pages.js

**Comment by F-loat** [comment]
你自己配置的啊 `entry: genEntry('./src/pages.js')`

**Comment by cooluid** [comment]
我有提前引入了的，const entry = genEntry('./src/router/index.js')

index.js
`module.exports = [
  {
    path: '/pages/index/index',
    name: 'index',
    config: {
      enablePullDownRefresh: true
    }
  },
  {
    path: '**/pages/user-center/user-center**',
    name: 'user-center',
    config: {
      enablePullDownRefresh: true
    }
  }
]
`

**Comment by F-loat** [comment]
你把 user-center 换个名字试下，可能是不支持这种写法？

**Comment by cooluid** [comment]
我试过了哦，当出现那个报错后，我还原了代码，一样编译不过，是不是node_modules 里面已经有缓存了。我删掉后再安装，就可以编译了

**Comment by F-loat** [comment]
是会有缓存，但是我这边没有遇到过类似的问题，方便的话可以提供一个复现 demo

**Comment by cooluid** [comment]
https://github.com/cooluid/xcool.git，你添加一个页面，然后在main.js里面指向这个页面为首页，再在router/index.js里面添加这个页面，就可以看到问题了

**Comment by F-loat** [comment]
👌我回去后试一下

**Comment by F-loat** [comment]
😓 你把 `name` 设置成 `index` 了，导致这个项目本身的文件被覆盖掉了，所以第二次运行就报错了
``` js
module.exports = [
  {
    path: '/pages/index/index',
    name: 'index',
    config: {
      enablePullDownRefresh: true
    }
  }
]
```

**Comment by cooluid** [comment]
。略显尴尬
