### ISSUE TITLE
访问子组件实例ref出现报错问题

### ISSUE THREAD

**Issue by Kellercai** [F-loat/mpvue-entry#71]
子组件：
```
<componentInterval
            ref="timeIntervalCom"/>

// 引用
this.$refs.timeIntervalCom.resetData()
```
编辑器报错
![image](https://user-images.githubusercontent.com/20681598/45214242-81780880-b2cc-11e8-9b7c-c750407b0ebb.png)
使用mpvue-entry之前是没有报错的。

**Comment by Kellercai** [comment]
还有就是pages.js的热更新问题，还是需要优化一下

**Comment by F-loat** [comment]
ref 和我这个库没什么关系啊。。热更新有空了会测下看看
