### ISSUE TITLE
使用mpvue-entry（1.5.3）后页面加载成功但是样式与点击事件等全部失效了。

### ISSUE THREAD

**Issue by luoxiaokun** [F-loat/mpvue-entry#73]
![image](https://user-images.githubusercontent.com/28639446/45338643-c6e45080-b5c0-11e8-9e7e-0681f3ca5209.png)

**Comment by F-loat** [comment]
和这个库应该没关系，建议排查下其他问题

**Comment by luoxiaokun** [comment]
大神可否指点一下，找了快一上午了...

**Comment by F-loat** [comment]
你检查下 webpack 的配置都有问题没

**Comment by luoxiaokun** [comment]
检查了一下，因为是对之前项目的改造，直接把demo里面webpack重要配置拷贝过来的。
<img width="729" alt="2018-09-11 1 08 40" src="https://user-images.githubusercontent.com/28639446/45339290-69ea9980-b5c4-11e8-9128-c92ef4164194.png">
