### ISSUE TITLE
没有生成js文件

### ISSUE THREAD

**Issue by coderliwenjie** [F-loat/mpvue-entry#74]
{
  "mpvue-entry": "^1.4.4",
   "mpvue-loader": "^1.0.15",
   "webpack-mpvue-asset-plugin": "^0.0.1"
}
{
  "mpvue-entry": "^1.5.0",
   "mpvue-loader": "^1.1.2",
  "webpack-mpvue-asset-plugin": "^0.1.0"
}
想问一下我将这三个包升级之后生成的目录里面没有js文件了
![image](https://user-images.githubusercontent.com/16144720/45341594-cf8f5380-b5cd-11e8-956a-ec030458a8c9.png)
编译并没有报错

**Comment by F-loat** [comment]
mpvue-loader 更新需要修改 webpack 的配置

**Comment by sonicsunsky** [comment]
我也遇到这个问题了

**Comment by F-loat** [comment]
那个模板生成的项目有问题吗

**Comment by sonicsunsky** [comment]
只改webpack.base.conf.js这个配置文件是不行的，跟原来项目仔细比对的话webpack.dev.conf.js和webpack.prod.conf.js，可能还有build和config文件下的其它文件都会有不同程度上的改变，直接用官方给的模板的话是可以的
