### ISSUE TITLE
打包卡住不动是怎么回事

### ISSUE THREAD

**Issue by sugar-zhang** [F-loat/mpvue-entry#75]
![image](https://user-images.githubusercontent.com/23262640/45465241-ead19e80-b746-11e8-861a-c2a27c48a896.png)
![image](https://user-images.githubusercontent.com/23262640/45465259-f91fba80-b746-11e8-8a21-4f38dced9834.png)
一直卡在这了

**Comment by sugar-zhang** [comment]
mpvue-loader@1.1.4

**Comment by F-loat** [comment]
使用 mpvue-entry 之前运行是正常的吗

**Comment by F-loat** [comment]
建议使用这个模板试下 https://github.com/F-loat/mpvue-quickstart

**Comment by pxzsl** [comment]
同样遇到这个问题了，版本一样
