### ISSUE TITLE
打包后vendor.js超过500KB

### ISSUE THREAD

**Issue by mschange** [F-loat/mpvue-entry#76]
你好，我用了mpvue-entry，处理了以前项目的main.js，加了pages.js，但是它打包后为什么比以前更大了，以及vendor.js超出了500KB，能给个思路吗

**Comment by F-loat** [comment]
这个库只是自动生成了之前的 main.js 文件，可以打开 node_modules/mpvue-entry/dist 文件夹查看生成的文件是否有问题

**Comment by mschange** [comment]
打包后的目录没有问题，。就是报了警告，说vendor.js超过了500KB，转ES5可能有问题

**Comment by F-loat** [comment]
这个库不直接影响打包结果

**Comment by mschange** [comment]
vendor打包的是第三方库，会不会有所影响呢

**Comment by mschange** [comment]
![01](https://user-images.githubusercontent.com/36876310/45471671-6726aa80-b764-11e8-9dd3-ae3f32ffe099.png)
![02](https://user-images.githubusercontent.com/36876310/45471672-6857d780-b764-11e8-9060-317e53a2b6e2.png)
你看下我这个目录有问题吗？谢谢

**Comment by F-loat** [comment]
mpvue-entry 是开发依赖，不会打包到最终的文件里的，你看下生成的入口文件有问题没有就行

**Comment by F-loat** [comment]
mpvue-entry 不直接影响代码打包结果，只是便于开发而已，要减小体积可以考虑进行分包，用不用 mpvue-entry 都可以实现，另外 vendor 超 500kb 没什么问题，而且 build 后会减小的

**Comment by mschange** [comment]
谢谢你的回答。
