### ISSUE TITLE
如果pages.js没更新，npm run dev会出现 app.json pages: []的错误

### ISSUE THREAD

**Issue by fighting1992** [F-loat/mpvue-entry#77]
必须要手动修改一下pages.js文件,比如加逗号、调换路由位置，再run dev，app.json才会正常，请问这是什么原因

**Comment by F-loat** [comment]
使用的版本说一下

**Comment by fighting1992** [comment]
1.5.2

**Comment by F-loat** [comment]
mpvue-loader 的版本？使用我提供的模板创建的项目会有这个问题不

**Comment by MDZZh** [comment]
osx系统也遇到这个问题 经观察后发现run dev时编译两次 第一次生成的小程序app.json是正常的  随后第二次小程序app.json被原有替换为page:[]

package.json{
   "mpvue-entry": "^1.4.7",
    "mpvue-loader": "^1.1.2"
}

**Comment by F-loat** [comment]
mpvue-entry^1.5.0 开始支持 mpvue-loader^1.1.0 的，可以的话提供个仓库复现，或者帮忙调试下看是哪儿的问题

**Comment by qinghua5453** [comment]
刚试了下，需要配置src/app.json 文件，配置对应的pages。这样打包出来的dist/app.json 才会在第一次npm run dev的时候 生成pages 目录

**Comment by s11831252** [comment]
作者您好,npm run dev会出现 app.json pages: []的错误。有解决方法嘛
package.json :
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "test",
  "author": "sch",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js",
    "lint": "eslint --ext .js,.vue src",
    "devH5": "webpack-dev-server --inline --progress --config buildH5/webpack.dev.conf.js",
    "buildH5": "node buildH5/build.js",
    "all": "npm run dev && npm run devH5"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "mpvue": "^1.0.11",
    "mpvue-router-patch": "^0.2.1",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.22.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.4.0",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "cssnano": "^3.10.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "glob": "^7.1.2",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy-middleware": "^0.18.0",
    "mpvue-entry": "^1.5.5",
    "mpvue-loader": "^1.1.2",
    "mpvue-template-compiler": "^1.0.11",
    "mpvue-webpack-target": "^1.0.0",
    "node-notifier": "^5.2.1",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^2.0.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.1.0",
    "postcss-loader": "^2.1.4",
    "postcss-mpvue-wxss": "^1.0.0",
    "postcss-url": "^7.3.2",
    "prettier": "~1.12.1",
    "px2rpx-loader": "^0.1.10",
    "relative": "^3.0.2",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.8.1",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.0.1",
    "vue-style-loader": "^4.1.2",
    "vue-loader": "^15.4.2",
    "vue-template-compiler": "^2.5.17",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware-hard-disk": "^1.12.0",
    "webpack-dev-server": "^3.0.0",
    "webpack-merge": "^4.1.0",
    "webpack-mpvue-asset-plugin": "^0.1.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by s11831252** [comment]
抽空看了一下配置部份，我使用vue init mpvue/mpvue-quickstart my-project创建的项目，原因是CopyWebpackPlugin插件再次将./src/app.json覆盖到dist
注释掉下列代码即可
//webpack.base.conf.js
//new CopyWebpackPlugin([{
//   from: '**/*.json',
//  to: ''
//  }], {
//  context: 'src/'
// }),
