### ISSUE TITLE
usingComponents ivew时 总是提示路径不对

### ISSUE THREAD

**Issue by fighting1992** [F-loat/mpvue-entry#78]
![image](https://user-images.githubusercontent.com/8445409/45543216-9b729780-b846-11e8-8282-fe0ec63e6510.png)
![image](https://user-images.githubusercontent.com/8445409/45543357-e9879b00-b846-11e8-829d-be39d6a27640.png)
请问这是什么原因呢

**Comment by F-loat** [comment]
这个和 mpvue-entry 没什么关系吧，那个组件你放的位置对吗

**Comment by cdll** [comment]
这么明显的misspelling问题: ``iview`` not ``ivew``
![image](https://user-images.githubusercontent.com/8576686/45791571-d0567280-bcbc-11e8-8789-f1d6352f85b3.png)
