### ISSUE TITLE
在 src/main.js 中使用 Vue.mixin() 会多次执行

### ISSUE THREAD

**Issue by auven** [F-loat/mpvue-entry#8]
src/mixin/index.js
```js
export default {
  onLoad() {
    console.warn('检查是否已经绑定了手机号码')
  }
}
```

src/main.js
```js
import Vue from 'vue'
import App from '@/App'
import mixin from '@/mixin'

Vue.config.productionTip = false
App.mpType = 'app'

Vue.mixin(mixin) <----- 这里

const app = new Vue(App)
app.$mount()

...
```

执行结果如图，`console.warn('检查是否已经绑定了手机号码')`被执行了多次
￼
![1524339804113](https://user-images.githubusercontent.com/23731087/39088134-60ba0bac-45df-11e8-9ae1-a160f0208aac.jpg)

原因：由于`mpvue-entry`这个插件的原理是以`src/main.js`为模板，因此每个入口文件都会复制`Vue.mixin(mixin)`，导致了`Vue.mixin(mixin)`语句执行了多次。

建议是不以 main.js 为模板，而是直接定义模板字符。
```js
// mpvue-entry 源码
...
  // 获取新旧入口文件模板
  // const template = String(fs.readFileSync(templatePath)).replace(/.*mpType.*/, '');
  const template = `
    import Vue from 'vue'
    import App from './index'

    const app = new Vue(App)
    app.$mount()

    export default {
    }
  `
  const bakTemplate = fs.existsSync(bakTemplatePath) ? String(fs.readFileSync(bakTemplatePath)) : '';

  const isTemplateChanged = template !== bakTemplate;
...
```

**Comment by F-loat** [comment]
比较好的实践是公用部分写在 main.js 里，只是某个页面用的话写在相应的 vue 文件里就好

**Comment by F-loat** [comment]
> 也可以全局注册混合对象。注意使用！ 一旦使用全局混合对象，将会影响到 所有 之后创建的 Vue 实例。使用恰当时，可以为自定义对象注入处理逻辑。

确实，之前没有考虑到这个问题，我把 Vue.mixin 相关的语句去掉这样处理吧， Vue.use 会自动防止多次注册，另外像 store 这种又确实每个 main.js 都需要引入，不然就得改 Vue.prototype.$store 才行

**Comment by F-loat** [comment]
所以说，各页面的 main.js 在实际使用中就是像你上面写那个模板字符串一样基本不会有其他改动吗。。

**Comment by auven** [comment]
store 这里我就是写的 Vue.prototype.$store ，挺好使的

**Comment by F-loat** [comment]
@auven 嗯，我改一下

**Comment by F-loat** [comment]
先这么解决了，使用固定的模板还会有其他的问题

**Comment by cncolder** [comment]
如果你的页面用了 class 写法, 同样会碰到上面的问题.
```js
@Component
export default class extends Vue {
}
```

问题出在 `src/main.js` 中的
```js
const app = new Vue({
  store,
  ...App
})
```

需要改成:
```js
Vue.prototype.$store = store
const app = new Vue(App)
```
