### ISSUE TITLE
分包 出现问题：pages pages/index 不应该在分包 subPackages[0] 中

### ISSUE THREAD

**Issue by qinghua5453** [F-loat/mpvue-entry#83]
{ 
  "pages": [
    "pages/index"
  ],
  "window": {
    "backgroundTextStyle": "light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "",
    "navigationBarTextStyle": "black",
    "backgroundTextStyle": "dark"
  },
  "subPackages": [{
    "root": "pages/",
    "pages": [
      "date",
      "pdate",
      "reserve",
      "login"
    ]
  }]
}
整体配置就是这样的。我的首页是不做分包配置的。其他页面考虑做分包配置。为了让首页加载更快。但配置好以后，爆出pages pages/index 不应该在分包 subPackages[0] 中 提示，请大佬指点。

**Comment by F-loat** [comment]
小程序本身的限制，分包和主包的根目录不能一致
