### ISSUE TITLE
TS 项目生成的页面 WXML 文件名称不对

### ISSUE THREAD

**Issue by banxi1988** [F-loat/mpvue-entry#84]
使用 mpvue-entry 之后。
发现生成的 页面的 WXML 文件不对。
下面是目前生成的文件：

```
home
├── Home.js
├── Home.js.map
├── Home.json
├── Home.vue.wxml
└── Home.wxss

0 directories, 5 files
```

显然 Home.vue.wxml 跟其他的不匹配，导致开发者工具找不到。

**Comment by F-loat** [comment]
其他依赖有更新吗，对比下生成的入口文件和你自己写的有区别没

**Comment by F-loat** [comment]
mpvue-loader 在 1.1.0 之后的版本生成的文件就是这样，需要同步修改 webpack 配置才行
