### ISSUE TITLE
dev刚启动项目会报错：未找到入口页面 app.json 中定义的 pages : []

### ISSUE THREAD

**Issue by wanCheng7** [F-loat/mpvue-entry#85]
![image](https://user-images.githubusercontent.com/24506126/46941270-58058600-d09d-11e8-8a6d-e8c35d687b24.png)
只是刚刚启动项目时会这样，点击任意一个文件之后保存热更新之后就不报错了！请问这是什么问题呢？

**Comment by wanCheng7** [comment]
我使用的版本是："mpvue-entry": "^1.5.6",同时更正一下并不是在任意界面保存都会没事，必须要保存pages.js文件才能恢复

**Comment by F-loat** [comment]
必现的问题吗，给个 demo 复现下？我提供的模板有这个问题没

**Comment by wanCheng7** [comment]
嗯，目前是首次打包必然会出现的，这个是我昨天出现这个问题的demo仓库，麻烦有时间看看，https://github.com/wanCheng7/mpvue-components。谢谢。还有，之前用mpvue-loader1.1.0之前的版本配合你1.4.7版本的mpvue-entry是没这个问题的

**Comment by F-loat** [comment]
和这个问题是一样的 https://github.com/F-loat/mpvue-entry/issues/77#issuecomment-428795122

**Comment by wanCheng7** [comment]
> 和这个问题是一样的 [#77 (comment)](https://github.com/F-loat/mpvue-entry/issues/77#issuecomment-428795122)

谢谢大佬！
