### ISSUE TITLE
按照文档将现有的小程序项目改了配置 但是出现了这个问题

### ISSUE THREAD

**Issue by Yuanyuanyuanc** [F-loat/mpvue-entry#87]
![c0813b35-f07e-4c73-8e52-4ceca198e406](https://user-images.githubusercontent.com/37654122/47983486-6845d980-e10e-11e8-9f34-bd2dae216eeb.png)

**Comment by F-loat** [comment]
movue-loader 和 mpvue-entry 分别是哪个版本？建议使用我提供的模板试试

**Comment by Yuanyuanyuanc** [comment]
"mpvue-loader": "^1.1.4", "mpvue-entry": "^1.4.2",
开始就用的您提示的版本 还是不可以 所以才换了这个

**Comment by F-loat** [comment]
我那个模板有什么问题吗，mpvue-entry 在 1.5 之后的版本才开始支持 1.1 以上版本的 mpvue-loader 的，不过你这个问题应该是 babel 配置的问题，换成 App.store = store 这种试试

**Comment by Yuanyuanyuanc** [comment]
我把项目挪到了您的这个模板下 现在是可以的了 但是我有点不明白分包文件夹下main.json是干嘛用的

**Comment by Yuanyuanyuanc** [comment]
是app.json的分支吗

**Comment by F-loat** [comment]
用了我这个插件后，页面就不需要 main.json 了，页面配置会由这个插件生成

**Comment by Yuanyuanyuanc** [comment]
感谢大佬 有问题再来请教
