### ISSUE TITLE
接入阿拉丁统计报错

### ISSUE THREAD

**Issue by zhangyt93** [F-loat/mpvue-entry#88]
按照官网的说明接入阿拉丁统计、
![image](https://user-images.githubusercontent.com/17688171/48325098-f8d06c80-e66e-11e8-93c9-d0720a33548e.png)
出现报错信息：
![image](https://user-images.githubusercontent.com/17688171/48325108-0685f200-e66f-11e8-965a-80b3af7587ae.png)

**Comment by F-loat** [comment]
使用的是哪个版本？可以的话先把 sdk 放在 src 目录下，可能是相对路径的处理有问题

**Comment by zhangyt93** [comment]
![image](https://user-images.githubusercontent.com/17688171/48541685-2419bc80-e8f8-11e8-89b1-78cf84ce2786.png)
直接引用的话会报这个错，mpvue-entry版本是1.2.4

**Comment by F-loat** [comment]
这个错误是缺个 babel 的插件，mpvue-entry 更新下试试

**Comment by zhangyt93** [comment]
更新到最新版还是报一样的错

**Comment by F-loat** [comment]
哪个错，后面那个配置下 babel，加个插件 [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports)

**Comment by F-loat** [comment]
插件好像记错了 https://github.com/Meituan-Dianping/mpvue/issues/919

**Comment by F-loat** [comment]
没事的
