### ISSUE TITLE
TypeError: Cannot read property 'for' of undefined

### ISSUE THREAD

**Issue by zaxlct** [F-loat/mpvue-entry#9]
![image](https://user-images.githubusercontent.com/14342431/39557513-c1d2af00-4eba-11e8-9a34-65bfe39ee862.png)

**Comment by zaxlct** [comment]
升级到 1.x  版本还是同样的错误

**Comment by zaxlct** [comment]
莫名其妙又好了不知道为啥。。。

**Comment by F-loat** [comment]
0.3.x 的最后一版应该是比较稳定的，暂时不要使用 1.0 之后的版本

**Comment by zaxlct** [comment]
@F-loat 
是的，换回 0.37 后正常了
