### ISSUE TITLE
生成的目录不对

### ISSUE THREAD

**Issue by Chen-WeiZhen** [F-loat/mpvue-entry#90]
![image](https://user-images.githubusercontent.com/18025841/49197843-74e6e600-f3cb-11e8-9379-711dbe295183.png)

生成的目录不对呢？
"mpvue-entry": "^1.5.9",
"mpvue": "^1.0.11",

**Comment by F-loat** [comment]
请多提供点信息好吧

**Comment by F-loat** [comment]
官方模板最近做了改动，先自定义下 dist 目录，后面会优化这里的判断

**Comment by F-loat** [comment]
看了下，由于这个模块在 webpack 启动前就执行了，好像没法自动获取输出目录，手动配置吧，另外建议使用我提供的模板初始化项目

``` js
MpvueEntry.getEntry({ dist: 'dist/wx' })
```

**Comment by F-loat** [comment]
这个问题最新版应该已经解决了
