### ISSUE TITLE
单文件多路径

### ISSUE THREAD

**Issue by yz-xlame** [F-loat/mpvue-entry#93]
能否实现单文件而多路由路径的情况呢？我尝试给路由写入多个
{
    path: 'pages/home'
    route: 'home'
},
{
    path: 'pages/home'
    route: 'main'
},
好像报错了Page[pages/tournament/match] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.

**Comment by F-loat** [comment]
业务场景是什么，route 这个属性应该只会影响编译后文件的路径

**Comment by yz-xlame** [comment]
@F-loat 因为两个页面差距较小，以路由为判断标准，希望2个路由能到同一个文件

**Comment by F-loat** [comment]
建议用同一个路由，传不同的参数

**Comment by yz-xlame** [comment]
@F-loat 我知道这个办法，但只有我是以路由为依据的吗

**Comment by F-loat** [comment]
想实现的话需要在路由的 api 上做处理，这个库即使能实现也是生成了两份代码
