### ISSUE TITLE
pages/index.js 出现脚本错误或者未正确调用 Page()

### ISSUE THREAD

**Issue by dog952777** [F-loat/mpvue-entry#94]
首先说下 项目创建使用的是mpvue模板 不是作者提供的 F-loat模板，我想借助作者的mpvue插件简化目录
下面是我使用的mpvue-entry版本、页面配置、报错信息的截图

![image](https://user-images.githubusercontent.com/22437517/50048597-79213c00-010b-11e9-941b-d41163372ead.png)
![image](https://user-images.githubusercontent.com/22437517/50048599-863e2b00-010b-11e9-8563-20c28ebb2d34.png)
![image](https://user-images.githubusercontent.com/22437517/50048601-8ccca280-010b-11e9-86f3-8899a8a4d840.png)

![image](https://user-images.githubusercontent.com/22437517/50048607-98b86480-010b-11e9-8f07-72f17dea6325.png)

**Comment by F-loat** [comment]
可以先把 main.js 里的 App.mpType = 'app' 去掉，改为在 app.vue 里加一个 mpType 属性，2.0版本的问题，后面会修正

**Comment by wufeng123456** [comment]
谢谢

**Comment by hotlove** [comment]
没有使用F-loat模板，自己到官方下载得mpvue 2.0模板，然后引入mpvue-entry 和mpvue-router-patch，刚开始得时候还是正常得，引入ivew得组件使用也是正常得，但是第二天打开后一直报"pages/count/index.js 出现脚本错误或者未正确调用 Page()"这个错误
![1](https://user-images.githubusercontent.com/19171186/61924776-e3506800-af9b-11e9-8a8e-7d39996907f8.png)
![2](https://user-images.githubusercontent.com/19171186/61924784-e77c8580-af9b-11e9-89f1-a47beb9da223.png)
![3](https://user-images.githubusercontent.com/19171186/61924786-e9464900-af9b-11e9-929c-e4daf82386d4.png)
![4](https://user-images.githubusercontent.com/19171186/61924792-ed726680-af9b-11e9-880c-540541dceecd.png)
![5](https://user-images.githubusercontent.com/19171186/61924796-f06d5700-af9b-11e9-89e2-4e3d99c4d263.png)
