### ISSUE TITLE
2.0.0-rc.8。dist多了3个文件导致报错。有没有稳定版

### ISSUE THREAD

**Issue by viryHd** [F-loat/mpvue-entry#97]
*dist/pagesIndex.js
*dist/packageALogs.js
*dist/pagesCounter.js

**Comment by viryHd** [comment]
不知道为什么，一run就多这三个文件

**Comment by F-loat** [comment]
项目里的 dist 目录吗，是用哪个模板初始化的

**Comment by viryHd** [comment]
vue init F-loat/mpvue-quickstart my-project，这个。
不是项目，是mpvue-entry这个依赖包，我一npm run dev ,mpvue-entry这个依赖包就多三个文件
我的项目刚跟着步骤搭建，到了npm run dev的时候报错

**Comment by viryHd** [comment]
感觉像是项目里的 output路径出了问题

**Comment by F-loat** [comment]
错误是什么，mpvue-entry 的 dist 目录里是会生成那三个入口文件的，这部分逻辑一直没变，可能后面会改成直接以 vue 文件为入口

**Comment by F-loat** [comment]
和这个错误一样吗，没改过配置的话不应该有这种错误的 https://github.com/F-loat/mpvue-quickstart/issues/20

**Comment by viryHd** [comment]
对就是一样的问题

**Comment by F-loat** [comment]
初始化安装依赖后运行就有这个错误？

**Comment by viryHd** [comment]
是的。

**Comment by viryHd** [comment]
![snipaste_2018-12-19_20-35-50](https://user-images.githubusercontent.com/42270969/50220623-cd5b4300-03cd-11e9-8fc6-33f98ae0150d.png)

**Comment by F-loat** [comment]
没问题啊。。

**Comment by F-loat** [comment]
移除 eslint 相关配置或重新初始化项目即可
