### ISSUE TITLE
新建组件 并在其他组件内引用不能热加载，必须npm run build后才会起作用

### ISSUE THREAD

**Issue by wufeng123456** [F-loat/mpvue-entry#99]

**Comment by wufeng123456** [comment]
新建basic-table组件 内容如下图
![0](https://user-images.githubusercontent.com/22437517/50437035-39d0c780-0923-11e9-9c4b-89d47aa54477.png)

在其他组件（journey组件）中调用，在开发者工具打开没有显示 选中元素发现宽高为0 如下图
![1](https://user-images.githubusercontent.com/22437517/50437055-4e14c480-0923-11e9-802e-f5cb63009499.png)

然后我查看dist文件
该组件的父组件（journey组件），basic-time组件（另外一个组件）和 basic-table不同 效果如下图
![2](https://user-images.githubusercontent.com/22437517/50437396-91236780-0924-11e9-8778-ce94d37b2429.png)

![4](https://user-images.githubusercontent.com/22437517/50437460-c7f97d80-0924-11e9-808e-9eeefcf8709b.png)
![3](https://user-images.githubusercontent.com/22437517/50437469-cd56c800-0924-11e9-82c6-274811d17a7b.png)


重新build后 查看build后的journey组件内容如下

![build](https://user-images.githubusercontent.com/22437517/50437515-f6775880-0924-11e9-8ec5-c3089869c217.png)

**Comment by F-loat** [comment]
可能是 mpvue 本身的问题，你用官方模板看下能不能复现，复现不了的话我这边看看
